================================================================================
Command Line:
	train_classifier.py ovr rwe /mnt/data/RWE/ -rwew 256 -rwed 4096 -ot svm -c 10 -cj 1 -e {"estimator__C": 100, "estimator__kernel": "rbf"}
================================================================================
================================================================================
Loading data...
================================================================================
================================================================================
Feature Type: rwe
	Window Size: 256
	Data points: 4,096
Number of features: 4,096
================================================================================
Using TensorFlow backend.
Traceback (most recent call last):
  File "train_classifier.py", line 540, in <module>
    main(args)
  File "train_classifier.py", line 251, in main
    X, y = ml.preprocess_data(X, y)
  File "/Source/malgazer/library/ml.py", line 156, in preprocess_data
    X_out, X_scaler = self.scale_features(X)
  File "/Source/malgazer/library/ml.py", line 628, in scale_features
    X_scaled = self.X_sc.fit_transform(X)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/base.py", line 517, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/preprocessing/data.py", line 590, in fit
    return self.partial_fit(X, y)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/preprocessing/data.py", line 612, in partial_fit
    warn_on_dtype=True, estimator=self, dtype=FLOAT_DTYPES)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/validation.py", line 444, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
MemoryError
